version: '3.8'
name: notifyme-project

services:
    mssql-server:
        image: mcr.microsoft.com/mssql/server:latest
        container_name: mssql-server
        hostname: mssql-server
        restart: always
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=qXz999W7M#
            - MSSQL_PID=Express
            - MSSQL_DB_NAME=NotifyMeDb
            # ACCEPT_EULA: Y
            # MSSQL_DB_NAME: NotifyMeDb
            # SA_PASSWORD: qXz999W7M#
        ports:
            - "1433:1433"
        volumes:
            - sqlsystem:/var/opt/mssql
            - sqldata:/var/opt/sqlserver/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        healthcheck:
            test: ["CMD", "sqlcmd", "-U", "sa", "-P", "qXz999W7M#", "-Q", "SELECT 1"]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            - notifyme-network
      
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports:
          - "5672:5672"  
          - "15672:15672" 
        environment:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        volumes:
          - rabbitmq_data:/var/lib/rabbitmq
        networks:
            - notifyme-network

    notifyme.api:
        image: ${DOCKER_REGISTRY-}notifymeapi
        build:
          context: .
          dockerfile: NotifyMe.API/Dockerfile
        container_name: notifyme.api
        hostname: notifyme.api
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:443;http://+:80
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "63349:80"
        healthcheck:
            test: ["CMD-SHELL", "curl -i http://localhost:80 || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 10s
        depends_on: 
            - mssql-server
            - rabbitmq
        networks:
            - notifyme-network

volumes:
  sqlsystem:
  sqldata:
  rabbitmq_data:

networks:
    notifyme-network:
        driver: bridge