version: '3.8'
name: notifyme-project

services:
    
    mssql-server:
        image: mcr.microsoft.com/mssql/server:latest
        container_name: mssql-server
        hostname: mssql-server
        restart: always
        environment:
            - COMPOSE_PROJECT_NAME=notifyme-project
            - ACCEPT_EULA=Y
            - SA_PASSWORD=qXz999W7M#
            - MSSQL_PID=Developer
            - MSSQL_DB_NAME=master
        ports:
            - "1433:1433"
        volumes:
            - mssql-data:/var/opt/mssql
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        healthcheck:
            test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "qXz999W7M#", "-Q", "SELECT 1"]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            - notifyme-network
      
    
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports:
            - "5672:5672"  
            - "15672:15672" 
        environment:
            - COMPOSE_PROJECT_NAME=notifyme-project
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        networks:
            - notifyme-network

    
    notifyme.api:
        image: ${DOCKER_REGISTRY-}notifymeapi
        build:
          context: .
          dockerfile: NotifyMe.API/Dockerfile
        container_name: notifyme.api
        hostname: notifyme.api
        restart: always
        environment:
            - COMPOSE_PROJECT_NAME=notifyme-project
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "63349:80"
        healthcheck:
            test: ["CMD-SHELL", "curl -i http://localhost:80/swagger/index.html || exit 1"]
            interval: 30s
            timeout: 15s
            retries: 5
            start_period: 10s
        depends_on: 
            mssql-server:
                condition: service_healthy
            rabbitmq:
                condition: service_started
        networks:
            - notifyme-network

volumes:
  mssql-data:
    # driver: local
  rabbitmq-data:
    # driver: local

networks:
    notifyme-network:
        driver: bridge