# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  notifyme.api:
    build:
      context: "C:\\dev\\NotifyMe"
      dockerfile: "NotifyMe.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net7.0/NotifyMe.API.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\rashi\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\rashi\\.nuget\\packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "notifymeapi:dev"
    ports:
    - "127.0.0.1:57004:57100"
    - "127.0.0.1:57204:57300"
    volumes:
    - "C:\\Users\\rashi\\AppData\\Roaming\\Microsoft\\UserSecrets:/root/.microsoft/usersecrets"
    - "C:\\Users\\rashi\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\dev\\NotifyMe\\NotifyMe.API:/app:rw"
    - "C:\\dev\\NotifyMe:/src:rw"
    - "C:\\Users\\rashi\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.2.2\\\
      Linux64:/riderDebugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 231.8109.136/bin:/riderLogsConf"
    - "C:\\Users\\rashi\\AppData\\Local\\JetBrains\\Rider2023.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2023_10_29_22_47_36:/riderLogs:rw"
    working_dir: "/app"
